import fireworks from './fireworks.js';
import confetti from './confetti.js';
import hearts from './hearts.js';
import money from './money.js';
import bam from './bam.js';
import vzhuh from './vzhuh.js';
import ogo from './ogo.js';
import haha from './haha.js';
import lasers from './lasers.js';
import sad from './sad.js';
import deal from './deal.js';
import wasted from './wasted.js';
import drama from './drama.js';
import aura from './aura.js';
import no from './no.js';
import yes from './yes.js';
import drumroll from './drumroll.js';
import crickets from './crickets.js';
import applause from './applause.js';

export const EFFECTS = [fireworks, confetti, hearts, money, bam, vzhuh, ogo, haha, lasers, sad, deal, wasted, drama, aura, no, yes, drumroll, crickets, applause];
