import replay from './replay.js';
import freeze from './freeze.js';
import rewind from './rewind.js';
import bam from './bam.js';
import yes from './yes.js';
import no from './no.js';
import drumroll from './drumroll.js';
import vzhuh from './vzhuh.js';
import haha from './haha.js';
import crickets from './crickets.js';
import fireworks from './fireworks.js';
import hearts from './hearts.js';
import applause from './applause.js';
import ogo from './ogo.js';
import sad from './sad.js';
import drama from './drama.js';
import wasted from './wasted.js';
import confetti from './confetti.js';
import lasers from './lasers.js';
import aura from './aura.js';
import deal from './deal.js';
import money from './money.js';

export const EFFECTS = [replay, freeze, rewind, bam, yes, no, drumroll, vzhuh, haha, crickets, fireworks, hearts, applause, ogo, sad, drama, wasted, confetti, lasers, aura, deal, money];
